### ISSUE TITLE
Investigation for Hosting Solutions and Deployment Strategy

### ISSUE THREAD

**Issue by Bardin08** [AcademicHubOrg/AcademicHub#114]
## Description
Investigate our new web application's most suitable hosting solution and deployment strategy. This includes evaluating cloud hosting providers (like AWS, Azure, GCP) and on-premises options, focusing on cost, scalability, security, performance, and compatibility with .NET and Google OAuth.

## Objectives
1. **Cloud Providers Analysis**: Assess major cloud providers for services, pricing, scalability, and .NET support.
2. **On-Premises Consideration**: Evaluate the feasibility of on-premises hosting.
3. **Security and Compliance**: Ensure the hosting solution aligns with security standards and compliance needs.
4. **Performance Metrics**: Evaluate potential solutions based on traffic, load handling, and performance.
5. **Cost Analysis**: Conduct a cost-benefit analysis of each hosting option.
6. **Integration Capability**: Assess integration ease with existing tools, especially Google OAuth.
7. **Vendor Support and SLAs**: Review hosting services' support and service level agreements.
8. **Recommendation Report**: Prepare a report summarizing findings with a hosting solution recommendation.

## Acceptance Criteria
1. Detailed analysis report of different hosting solutions.
2. Comparative analysis table of hosting options.
3. Final recommendation on suitable hosting solution and deployment strategy.
4. Presentation of findings to stakeholders for decision-making.

**Comment by YaroslavKSE** [comment]
I chose "Digital Ocean" because it provides good services, affordable and competative pricing, support of scalability. Moreover, we have experience working with Digital Ocean, therefore is is the most suitable variant for us.
