### ISSUE TITLE
Create New Cloud Account

### ISSUE THREAD

**Issue by Bardin08** [AcademicHubOrg/AcademicHub#115]
## Description
Create a new account with the selected cloud service provider. This task is a critical initial step in establishing our cloud infrastructure for the application.

## Tasks
1. **Provider Selection Confirmation**: Confirm the chosen cloud provider based on prior evaluation. #114
2. **Account Registration**: Register for a new account with the provider.
3. **Verification Process**: Complete any required verification steps for account activation.
4. **Billing Setup**: Configure billing details, including payment methods and budget limits.
5. **Initial Access Configuration**: Set up primary access credentials and account security settings.
6. **Account Documentation**: Document the account creation process, including credentials and configurations.

## Acceptance Criteria
1. A fully registered and verified cloud account with the selected provider.
2. Billing details are accurately set up and documented.
3. Primary access credentials established and secured.
4. Comprehensive documentation of the account creation process.

**Comment by YaroslavKSE** [comment]
Registred in digital ocean. Created droplet. 
**Screenshots attached below:**
![image](https://github.com/AcademicHubOrg/AcademicHub/assets/94047397/2c880553-43f9-4c49-a4cb-12f4c22cac4a)
![image](https://github.com/AcademicHubOrg/AcademicHub/assets/94047397/e52a9f20-5f5a-49df-a9eb-d15d45672bd2)
