### ISSUE TITLE
Manual Deployment (First Time Only)

### ISSUE THREAD

**Issue by Bardin08** [AcademicHubOrg/AcademicHub#117]
## Description
Perform the first deployment of our web application manually. This initial deployment will help us understand the deployment process in detail and identify any potential issues in the environment.

## Tasks
1. **Pre-Deployment Checklist**: Verify that all pre-deployment requirements, such as configurations and environment settings, are in place.
2. **Deployment Plan Review**: Review the deployment plan to ensure an understanding of each step.
3. **Manual Deployment**: Manually deploy the application to the environment.
4. **Monitoring and Verification**: Closely monitor the deployment process and verify that the application is running as expected in the environment.
5. **Issue Logging**: Log any issues encountered during the deployment for future reference and improvement.
6. **Post-Deployment Testing**: Conduct thorough testing to ensure all features work correctly in the production environment.
7. **Documentation**: Document the deployment process, including any challenges faced and how they were resolved.

## Acceptance Criteria
1. Successful manual deployment of the application to the environment.
2. The application runs smoothly in the environment with all functional features.
3. Documentation of the deployment process and any issues encountered.
4. Post-deployment testing was completed with satisfactory results.

**Comment by YaroslavKSE** [comment]
Successfull manual deploy. Closes with #137 #138 
**Link to web cite:** 
http://165.22.66.19:3000/
